# Generated by Django 5.2.3 on 2025-07-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser_custom',
            field=models.BooleanField(default=False),
        ),
    ]
